arena/arena/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('person.urls', namespace='person')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

arena/person/urls.py
from django.urls import path
from . import views

app_name = 'person'

urlpatterns = [
    path('', views.index, name='index'),   # Инфа о всей бойцах
    path('profile/<str:username>/',        # Профиль пользователя
         views.profile, name='profile'),
    path('paladin_create/', views.paladin_create, name='paladin_create'),
    path('warrior_create/', views.warrior_create, name='warrior_create'),
    path('fight_vs_someone/<str:username>/fight/',  # Битва против рандома
         views.fight_vs_someone, name='fight_vs_someone'),
    path('fight_vs_u_want/<str:username>/<int:enemy_id>/fight/',
         views.fight_vs_u_want, name='fight_vs_u_want'),  # Против конкретного
]

arena/templates/create/paladin.html
{% extends 'base.html' %}
  {% block title %}
  Новый паладин
  {% endblock %}
  {% block content %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header"  style="background-color: #BF442A">       

               Окно персонажа
        
            </div>
            <div class="card-body" style="background-color: #232323">

              <form method="post" enctype="multipart/form-data" action="{% url 'person:paladin_create' %}">
                {% csrf_token %}

                {% for field in form %} 

                  <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %} style="background-color: #232323">
                    <label for="{{ field.id_text }}" class="form-group row my-6 p-3" >{{ field.label }}
                      {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}</label>
                        <div class="col-md-12">
                          {{ field }}
                        </div>                
                  </div>

                {% endfor %}

                <div class="d-flex justify-content-end" style=margin-top:3% >
                  <button type="submit" class="btn btn-warning " style="color: #232323; text-decoration: none">
                    Добавить
                  </button>  
                </div>
              </form> 
          </div>
        </div>
      </div>
    </div>
  {% endblock %}